services:
  pulsar-products-service:
    image: yaninyzwitty/pulsar-products-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    configs:
      - source: my_config
        target: ./my_config.yaml
    networks:
      - private_network

configs:
  my_config:
    file: config.yaml
networks:
  private_network:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.100.0/24"
          gateway: "192.168.100.1"